spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.maomao.pojo
server:
  port: 8001

page helper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    com:
      maomao:
        mapper: debug
